#include <unistd.h>
#include <sys/wait.h>
#include <poll.h>
#include <signal.h>
#include <chrono>
#include <cerrno>
#include <iostream>
#include <string>
#include <vector>
#include <optional>
#include <stdexcept>
using namespace std;
struct Child {pid_t pid; int input, output; ~Child(){if(input>=0)close(input);if(output>=0)close(output); if(pid>0){kill(pid,SIGKILL);waitpid(pid,nullptr,0);}}};
Child launch(string exe){int in[2],out[2];if(pipe(in)||pipe(out))throw runtime_error("pipe");pid_t p=fork();if(p<0)throw runtime_error("fork");if(p==0){dup2(in[0],STDIN_FILENO);dup2(out[1],STDOUT_FILENO);close(in[0]);close(in[1]);close(out[0]);close(out[1]);execl(exe.c_str(),exe.c_str(),(char*)nullptr);_exit(127);}close(in[0]);close(out[1]);return Child{p,in[1],out[0]};}
void sendline(Child& c,string s){s+='\n';while(!s.empty()){auto n=write(c.input,s.data(),s.size());if(n<=0)throw runtime_error("ENGINE_STDIN_CLOSED");s.erase(0,(size_t)n);}}
struct Reader {Child &c;string buffer; string line(int timeout_ms){auto deadline=chrono::steady_clock::now()+chrono::milliseconds(timeout_ms);for(;;){auto i=buffer.find('\n');if(i!=string::npos){string out=buffer.substr(0,i);buffer.erase(0,i+1);if(!out.empty()&&out.back()=='\r')out.pop_back();return out;}int remaining=(int)chrono::duration_cast<chrono::milliseconds>(deadline-chrono::steady_clock::now()).count();if(remaining<=0)throw runtime_error("ENGINE_TIMEOUT");pollfd f{c.output,POLLIN,0};int rc=poll(&f,1,remaining);if(rc==0)throw runtime_error("ENGINE_TIMEOUT");if(rc<0){if(errno==EINTR)continue;throw runtime_error("ENGINE_POLL_ERROR");}char buf[2048];int n=read(c.output,buf,sizeof(buf));if(n<=0)throw runtime_error("ENGINE_EOF");buffer.append(buf,n);if(buffer.size()>1048576)throw runtime_error("ENGINE_OUTPUT_OVERFLOW");}}};
void until(Reader &r,string token,int ms){auto end=chrono::steady_clock::now()+chrono::milliseconds(ms);for(;;){int remain=(int)chrono::duration_cast<chrono::milliseconds>(end-chrono::steady_clock::now()).count();if(remain<=0)throw runtime_error("ENGINE_TIMEOUT_WAITING_"+token);auto s=r.line(remain);if(s==token)return;}}
int main(int argc,char**argv){try{if(argc!=5){cerr<<"usage: uci_probe ENGINE_ABSOLUTE_PATH FEN MOVE_A MOVE_B\n";return 2;}string exe=argv[1],fen=argv[2],a=argv[3],b=argv[4];if(exe.empty()||exe[0]!='/'||access(exe.c_str(),X_OK))throw runtime_error("ENGINE_EXECUTABLE_REQUIRED");if(fen.find('\n')!=string::npos||a.find_first_not_of("abcdefgh12345678qrbn")!=string::npos||b.find_first_not_of("abcdefgh12345678qrbn")!=string::npos)throw runtime_error("INVALID_REQUEST");Child child=launch(exe);Reader r{child,""};sendline(child,"uci");until(r,"uciok",3000);sendline(child,"isready");until(r,"readyok",3000);sendline(child,"setoption name MultiPV value 2");sendline(child,"isready");until(r,"readyok",3000);sendline(child,"ucinewgame");sendline(child,"position fen "+fen);sendline(child,"go depth 8 searchmoves "+a+" "+b);optional<string> bm;vector<string> info;auto deadline=chrono::steady_clock::now()+chrono::seconds(12);while(!bm){int remain=(int)chrono::duration_cast<chrono::milliseconds>(deadline-chrono::steady_clock::now()).count();if(remain<=0)throw runtime_error("ENGINE_TIMEOUT_BESTMOVE");string s=r.line(remain);if(s.rfind("info ",0)==0&&s.find(" score ")!=string::npos)info.push_back(s);if(s.rfind("bestmove ",0)==0)bm=s.substr(9);}sendline(child,"quit");cout<<"{\"status\":\"RAW_UCI_OBSERVATION_ONLY\",\"bestmove\":\""<<*bm<<"\",\"info_lines\":[";for(size_t i=0;i<info.size();++i){if(i)cout<<',';cout<<'"';for(char c:info[i]){if(c=='"'||c=='\\')cout<<'\\';if(c!='\r'&&c!='\n')cout<<c;}cout<<'"';}cout<<"],\"legality_verified\":false,\"explanation_granted\":false,\"scientific_preseal\":false}\n";return 0;}catch(const exception& e){cerr<<"UCI_PROBE_FAIL:"<<e.what()<<'\n';return 3;}}
